---
title: "Jubilee Park"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "..") })
---
<html lang="en">
  <header>
    <meta charset="utf-8"/>
    <title>Jubilee Park</title>
  </header>
  <body>

```{r setup, include=FALSE}
library(flexdashboard)
library(accessrmd)
```

Elevation Shots {.tabset}
-----------------------------------------------------------------------

### 2020s Colour

```{r, warning=FALSE}
access_img(img = "../www/images/Rogerstone Jubilee Park 2020 (Colour).JPG",
           alt = "Colour aerial photo of Jubilee Park estate circa 2020")
```


### 2020s B&W

```{r, warning=FALSE}
access_img(img = "../www/images/Rogerstone Jubilee Park 2020 (B&W).jpg",
           alt = "Black & white aerial photo of Jubilee Park estate circa 2020")
```

### 1980s B&W

```{r, warning=FALSE}
 access_img(img = "../www/images/Rogerstone Alcan Original.JPG",
            alt = "Black & white Aerial photo of Alcan estate circa 1980")
```



  </body>
</html>